---
version: 2
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/circleci-python-examples
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Set up test environment
          command: |
              mkdir test-results
              pip install pipenv
              pipenv install
              curl -H 'Cache-Control: no-cache'  https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - run:
          name: Install Python prerequsites
          command: |
              pip install -r py/requirements.txt
      - save_cache:  # cache Python deps using Pipfile checksum as the cache-key
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.10/site-packages"
      - run:
          name: Lint check
          command: |
              pipenv run flake8 |tee test-results/flake8_lint_report.txt
      - run:
          name: Unit testing
          command: |
              pipenv run pytest -v --junitxml=test-results/junit.xml
      - run:
          name: License check
          command: |
              fossa init
              fossa analyze
      - store_test_results:
          path: test-results
