version: 2
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/circleci-python-examples
    docker:
      - image: circleci/python:3.7.3
    steps:
    - checkout
    - run: 
      command: |
          sudo pip install pipenv
          pipenv install
    - run:
          command: |
            pipenv run pytest -v
    - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
